import os

PROJECT_DIRECTORY = os.path.dirname(os.path.abspath(__file__))
ASSIGN_PERSONALITY_DIRECTORY = 'assign_personality'
REPORTS_DIRECTORY = 'reports'

SOURCE_DIRECTORY = 'source_data'
OUTPUT_DIRECTORY = 'output_data'


CSV_FORMDATA_INPUT_FILE_PATH = os.path.join(
    PROJECT_DIRECTORY,
    ASSIGN_PERSONALITY_DIRECTORY,
    SOURCE_DIRECTORY,
    'Form_data.csv'
)
FORM_DELIMITER = ','
FORM_FILE_ENCODING = 'utf-8'

CSV_USERDATA_INPUT_FILE_PATH = os.path.join(
    PROJECT_DIRECTORY,
    ASSIGN_PERSONALITY_DIRECTORY,
    SOURCE_DIRECTORY,
    'Sapientia_data.csv'
)
SAPIENTIA_DELIMITER = ';'
SAPIENTIA_FILE_ENCODING = 'utf-8-sig'


"""Assigned files path"""
ASSIGNED_FILES_DELIMITER = ';'
ASSIGNED_FILES_ENCODING = 'utf-8'
CSV_ASSIGNED_TRANSPORT_FILE_PATH = os.path.join(
    PROJECT_DIRECTORY,
    ASSIGN_PERSONALITY_DIRECTORY,
    OUTPUT_DIRECTORY,
    'Alumnos_profiles_car_ownership.csv'
)
CSV_ASSIGNED_SMOKER_FILE_PATH = os.path.join(
    PROJECT_DIRECTORY,
    ASSIGN_PERSONALITY_DIRECTORY,
    OUTPUT_DIRECTORY,
    'Alumnos_profiles_smoker.csv'
)
CSV_ASSIGNED_ELOQUENCE_FILE_PATH = os.path.join(
    PROJECT_DIRECTORY,
    ASSIGN_PERSONALITY_DIRECTORY,
    OUTPUT_DIRECTORY,
    'Alumnos_profiles_eloquence.csv'
)
CSV_ASSIGNED_MUSIC_TASTE_FILE_PATH = os.path.join(
    PROJECT_DIRECTORY,
    ASSIGN_PERSONALITY_DIRECTORY,
    OUTPUT_DIRECTORY,
    'Alumnos_profiles_music_taste.csv'
)
CSV_ASSIGNED_ITINERARY_FILE_PATH = os.path.join(
    PROJECT_DIRECTORY,
    ASSIGN_PERSONALITY_DIRECTORY,
    OUTPUT_DIRECTORY,
    'Alumnos_profiles_itinerary.csv'
)

"""Reports files path"""
CSV_REPORT_CARS_FILE_PATH = os.path.join(
    PROJECT_DIRECTORY,
    REPORTS_DIRECTORY,
    OUTPUT_DIRECTORY,
    'cars.csv'
)
CSV_REPORT_DISTANCE_FILE_PATH = os.path.join(
    PROJECT_DIRECTORY,
    REPORTS_DIRECTORY,
    OUTPUT_DIRECTORY,
    'distance.csv'
)


"""Field names"""
FIELDNAME_UUID = 'UUID'
FIELDNAME_CAREER = 'CAREER'
FIELDNAME_SEX = 'SEX'
FIELDNAME_ADDRESS = 'ADDRESS'
FIELDNAME_LATITUDE = 'LATITUDE'
FIELDNAME_LONGITUDE = 'LONGITUDE'
FIELDNAME_TRANSPORT = 'TRANSPORT'
FIELDNAME_TOA = 'TIME_OF_ARRIVAL'
FIELDNAME_TOD = 'TIME_OF_DEPARTURE'
FIELDNAME_SMOKER = 'SMOKER'
FIELDNAME_ELOQUENCE = 'ELOQUENCE_LEVEL'
FIELDNAME_MUSIC_TASTE = 'MUSIC'


"""Database configurations"""
DATABASE_NAME = 'alumni.sqlite3'
DATABASE = os.path.join(
    PROJECT_DIRECTORY,
    DATABASE_NAME
)

DATABASE_SMARTTRAFFIC = {
    "NAME": "smarttraffic",
    "USER": "postgres",
    "PASSWORD": "postgres",
    "HOST": "127.0.0.1",
    "PORT": "5432",
}

DATABASE_MAP = {
    "NAME": "asuncion",
    "USER": "postgres",
    "PASSWORD": "postgres",
    "HOST": "127.0.0.1",
    "PORT": "5432",
}


"""Table names for database"""
DATABASE_TABLE_ALUMNI = 'alumni'
DATABASE_TABLE_CARS = 'alumni_cars'
DATABASE_TABLE_ELOQUENCE = 'alumni_eloquence'
DATABASE_TABLE_SMOKER = 'alumni_smoker'
DATABASE_TABLE_MUSIC = 'alumni_music'
DATABASE_TABLE_ITINERARY = 'alumni_itinerary'
DATABASE_TABLE_AUTH = 'alumni_auth'
DATABASE_TABLE_USER_ITINERARY = 'alumni_useritinerary'


"""Uploading to server settings"""
BACKEND_STAFF_TOKEN = '00cc9b7f5106078fb734d998f255daf92a1628f8'
SERVER_URL = 'http://127.0.0.1:51328'
API_URL = f'{SERVER_URL}/api/ucarpooling'
UCARPOOLING_APP_TOKEN = 'ee27d9ae740016bfbf1a903c154eb4439b03afaa'
USER_URL = f'{API_URL}/users/'
USER_ITINERARY_URL = f'{API_URL}/itinerary/'
AUTH_TOKEN_URL = f'{API_URL}/auth-token/'
CARPOOL_URL = f'{API_URL}/carpool/'

"""Simulator settings"""
TOLERANCE_PERCENTAGE = 100.0
ACCEPTANCE_THRESHOLD = 0.5
POOLERS_LIMIT_PER_CAR = 4
LIMIT_USERS = 600
