import os


ASSIGN_PERSONALITY_DIRECTORY = 'assign_personality'
PROJECT_DIRECTORY = os.path.dirname(os.path.abspath(__file__))

SOURCE_DIRECTORY = 'source_data'
OUTPUT_DIRECTORY = 'output_data'


CSV_FORMDATA_INPUT_FILE_PATH = os.path.join(
    PROJECT_DIRECTORY,
    ASSIGN_PERSONALITY_DIRECTORY,
    SOURCE_DIRECTORY,
    'Form_data.csv'
)
FORM_DELIMITER = ','
FORM_FILE_ENCODING = 'utf-8'

CSV_USERDATA_INPUT_FILE_PATH = os.path.join(
    PROJECT_DIRECTORY,
    ASSIGN_PERSONALITY_DIRECTORY,
    SOURCE_DIRECTORY,
    'Sapientia_data.csv'
)
SAPIENTIA_DELIMITER = ';'
SAPIENTIA_FILE_ENCODING = 'utf-8-sig'


"""Assigned files path"""
ASSIGNED_FILES_DELIMITER = ';'
ASSIGNED_FILES_ENCODING = 'utf-8'
CSV_ASSIGNED_TRANSPORT_FILE_PATH = os.path.join(
    PROJECT_DIRECTORY,
    ASSIGN_PERSONALITY_DIRECTORY,
    OUTPUT_DIRECTORY,
    'Alumnos_profiles_car_ownership.csv'
)
CSV_ASSIGNED_SMOKER_FILE_PATH = os.path.join(
    PROJECT_DIRECTORY,
    ASSIGN_PERSONALITY_DIRECTORY,
    OUTPUT_DIRECTORY,
    'Alumnos_profiles_smoker.csv'
)
CSV_ASSIGNED_ELOQUENCE_FILE_PATH = os.path.join(
    PROJECT_DIRECTORY,
    ASSIGN_PERSONALITY_DIRECTORY,
    OUTPUT_DIRECTORY,
    'Alumnos_profiles_eloquence.csv'
)
CSV_ASSIGNED_MUSIC_TASTE_FILE_PATH = os.path.join(
    PROJECT_DIRECTORY,
    ASSIGN_PERSONALITY_DIRECTORY,
    OUTPUT_DIRECTORY,
    'Alumnos_profiles_music_taste.csv'
)
CSV_ASSIGNED_ITINERARY_FILE_PATH = os.path.join(
    PROJECT_DIRECTORY,
    ASSIGN_PERSONALITY_DIRECTORY,
    OUTPUT_DIRECTORY,
    'Alumnos_profiles_itinerary.csv'
)


"""Field names"""
FIELDNAME_UUID = 'UUID'
FIELDNAME_CAREER = 'CAREER'
FIELDNAME_SEX = 'SEX'
FIELDNAME_ADDRESS = 'ADDRESS'
FIELDNAME_LATITUDE = 'LATITUDE'
FIELDNAME_LONGITUDE = 'LONGITUDE'
FIELDNAME_TRANSPORT = 'TRANSPORT'
FIELDNAME_TOA = 'TIME_OF_ARRIVAL'
FIELDNAME_TOD = 'TIME_OF_DEPARTURE'
FIELDNAME_SMOKER = 'SMOKER'
FIELDNAME_ELOQUENCE = 'ELOQUENCE_LEVEL'
FIELDNAME_MUSIC_TASTE = 'MUSIC'


"""Database configurations"""
DATABASE_NAME = 'alumni.sqlite3'
DATABASE = os.path.join(
    PROJECT_DIRECTORY,
    DATABASE_NAME
)

"""Table names for database"""
DATABASE_TABLE_ALUMNI = 'alumni'
DATABASE_TABLE_CARS = 'alumni_cars'
DATABASE_TABLE_ELOQUENCE = 'alumni_eloquence'
DATABASE_TABLE_SMOKER = 'alumni_smoker'
DATABASE_TABLE_MUSIC = 'alumni_music'
DATABASE_TABLE_ITINERARY = 'alumni_itinerary'
DATABASE_TABLE_AUTH = 'alumni_auth'
DATABASE_TABLE_USER_ITINERARY = 'alumni_useritinerary'


"""Uploading to server settings"""
SERVER_URL = 'http://127.0.0.1:56121'
UCARPOOLING_APP_TOKEN = '6dbb6c8b9c9daeb66b64e6aaa7e8f3d338e4ac68'
USER_URL = f'{SERVER_URL}/api/ucarpooling/users/'
USER_ITINERARY_URL = f'{SERVER_URL}/api/ucarpooling/itinerary/'
AUTH_TOKEN_URL = f'{SERVER_URL}/api/ucarpooling/auth-token/'
