import os

PROJECT_DIRECTORY = os.path.dirname(os.getcwd())


SOURCE_DIRECTORY = 'source_data'
OUTPUT_DIRECTORY = 'output_data'


CSV_FORMDATA_INPUT_FILE_PATH = os.path.join(PROJECT_DIRECTORY, SOURCE_DIRECTORY, 'Formulario.csv')
FORM_DELIMITER = ','

CSV_USERDATA_INPUT_FILE_PATH = os.path.join(PROJECT_DIRECTORY, SOURCE_DIRECTORY, 'Alumnos_Campus_Geocoded.csv')
SAPIENTIA_DELIMITER = ';'

CSV_OUTPUT_FILE_PATH = os.path.join(PROJECT_DIRECTORY, OUTPUT_DIRECTORY, 'Alumnos_profiles_car_ownership.csv')
OUTPUT_FILES_DELIMITER = ';'

"""Field names"""
FIELDNAME_TRANSPORT = 'TRANSPORT'
FIELDNAME_UUID = 'UUID'
FIELDNAME_LATITUDE = 'LATITUD'
FIELDNAME_LONGITUDE = 'LONGITUD'
FIELDNAME_TOA = 'TIME_OF_ARRIVAL'
FIELDNAME_TOD = 'TIME_OF_DEPARTURE'

